### ISSUE TITLE
Investigate Electron Security Warning at start up

### ISSUE THREAD

**Issue by colfax23** [stake-house/wagyu-key-gen#11]
![Screen Shot 2021-07-09 at 3 02 40 PM](https://user-images.githubusercontent.com/914240/125124835-b7feaf00-e0c6-11eb-8624-9d54852c8f6a.png)

**Comment by remyroy** [comment]
Let me check this one as well.

**Comment by remyroy** [comment]
The error is gone when starting the application from a bundle. Let me see if we can also *fix* it in dev.

**Comment by remyroy** [comment]
@colfax23 Do you remember why you disabled context isolation in https://github.com/stake-house/wagyu-key-gen/blob/main/src/electron/index.ts#L40 ?

**Comment by remyroy** [comment]
I don't think we should change anything here since this warning is removed in our bundle. Closing this one.
