### ISSUE TITLE
The default visual style of the `<Link>` elements seems a bit off.

### ISSUE THREAD

**Issue by remyroy** [stake-house/wagyu-key-gen#114]
The text seems a little smaller and hard to read on my screen. It's also hard to tell it's a link. Maybe it should be the same size with a default underline.

![](https://cdn.discordapp.com/attachments/878318728364818452/906643150674731078/links.png)

Maybe they should include a target symbol like on Obsidian:

![](https://cdn.discordapp.com/attachments/878318728364818452/906643457634893834/link-target.png)

**Comment by remyroy** [comment]
This might not be relevant anymore with the recent link changes in #120 . Should we close this one @colfax23 ?

**Comment by colfax23** [comment]
Yep, closing.
