### ISSUE TITLE
Prater & Mainnet secret recovery phrase screens are different

### ISSUE THREAD

**Issue by shawynot** [stake-house/wagyu-key-gen#128]
Threw me off when I moved from test to main to have a different method to confirm my mnemonic. 

![image](https://user-images.githubusercontent.com/42036966/147121408-1f2575bd-07d6-4cd1-918f-b3035eb77959.png)

**Comment by remyroy** [comment]
This is on purpose. We want higher confidence on user having stored their secret recovery phrase when on mainnet.
