### ISSUE TITLE
Check of seed looks different on prater & mainnet

### ISSUE THREAD

**Issue by stefa2k** [stake-house/wagyu-key-gen#147]
Using version `v1.4.0-6b621ba` the screen of the verification of the seed phrase looks differently on mainnet and prater:

Mainnet looks like this:
![image](https://user-images.githubusercontent.com/54934211/170855749-fad367ae-c99b-4ff8-a6b5-67b878a30900.png)

Prater looks like this:
![image](https://user-images.githubusercontent.com/54934211/170855765-67375765-a23a-4d49-bd6d-d0d10954a8e4.png)

**Comment by remyroy** [comment]
It's meant to be this way. We wanted a stronger confidence that the user actually wrote down their mnemonic for mainnet.
