### ISSUE TITLE
MacOS shortcuts of other apps stop working when Wagyu Key Gen runs

### ISSUE THREAD

**Issue by stefa2k** [stake-house/wagyu-key-gen#148]
On MacOS 12.3 when Wagyu Key Gen version `v1.4.0-6b621ba` is running in the background and I e. g. try CMD+R to refresh a page in a browser (doesn't matter which one, tested with FF, Chrome) the browser does nothing and instead the browser windows of the electron app of Wagyu Key Gen get's a refresh.

**Comment by remyroy** [comment]
We have this part which might be related: https://github.com/stake-house/wagyu-key-gen/blob/main/src/electron/index.ts#L69

It probably should not be a global shortcut.

**Comment by remyroy** [comment]
This was fixed with v1.6.0.
