### ISSUE TITLE
UX for providing a withdrawal address

### ISSUE THREAD

**Issue by wackerow** [stake-house/wagyu-key-gen#155]
## Issue
Recently #153 updated the path for users to be forced to provide a withdrawal address. This change was in anticipation of changes coming to the `staking-deposit-cli` tool where a PR was up to make this required, but I may have jumped the gun a bit.

After more discussion, concerns have been raised regarding removing the option for users to opt-out of receiving automatic withdrawals. This could be desired for various reasons, and more importantly it's probably not best to remove this option when UX could be used to offer both.

I can put up a PR to revert the previous changes, which removed the toggle for "Use Advanced Inputs" and simply made the field required.

Beyond that reversion, I wanted to open this issue for discussion if folks had any input on improving the UX here for users.

I think it would be nice to see the address input visible by default, and change the toggle to some form of "opt-out" input, perhaps reusing the toggle or maybe a checkbox. I think the majority of users are going to prefer having excess balance delivered automatically, and we should accommodate that to make that the default flow, while still providing an easy clear way to disable.

**Comment by remyroy** [comment]
This was completed with 07fa66c4956edf6b2427b8553fec65288d200691
