### ISSUE TITLE
Support 12-word mnemonic as staking-deposit-cli does (i.e., relax the front-end validation logic)

### ISSUE THREAD

**Issue by yzhuang** [stake-house/wagyu-key-gen#164]
By default, both staking-deposit-cli and Wagyu key gen would produce 24-word mnemonic.
However, when using an existing mnemonic, staking-deposit-cli also supports using 12-word mnemonic.

We (stakefish) have found that this is actually a very common case because many users confused their MetaMask mnemonic and BLS mnemonic, and they reused their 12-word MetaMask mnemonic with staking-deposit-cli.

Wagyu has a front-end validation that requires the mnemonic to be 24-word long, which should be relaxed to match the underlying staking-deposit-cli.

**Comment by yzhuang** [comment]
See https://github.com/stake-house/wagyu-key-gen/blob/main/src/react/components/MnemonicImport.tsx#L43

**Comment by dvvvsh** [comment]
any solution to this?
