### ISSUE TITLE
Cannot enter mnemonic manually in release 1.8.0 due to aggressive trimming of spaces

### ISSUE THREAD

**Issue by haurog** [stake-house/wagyu-key-gen#177]
Trying to separate seed words using space does not work in release 1.8.0. Pressing space does not add an empty space at the end of the word. It works adding spaces in the middle of words. Probably trimming empty spaces during entering the mnemonic is a bit too aggressive.

**Comment by remyroy** [comment]
I agree. Let's remove that.

**Comment by remyroy** [comment]
As a temporary workaround, you can use a punctuation sign, but we'll definitly fix this and release a new version with this fix.
