### ISSUE TITLE
How did you build release binaries?

### ISSUE THREAD

**Issue by SergeevDmitry** [stake-house/wagyu-key-gen#191]
Hello.

I tried to build binaries myself following all provided instructions, but when I run it on fresh machines (linux/windows) and try to create new mnemonic it shows various errors depending on a platform

Ubuntu

![wagyu-error](https://github.com/stake-house/wagyu-key-gen/assets/4901764/80af2150-db70-4853-9cb9-8359f2e53cee)

Windows

![image](https://github.com/stake-house/wagyu-key-gen/assets/4901764/1be926a1-f5c2-4ac7-bd8a-68a1495ac596)

Your release binaries work good on the same machines.

I found this [issue](https://github.com/stake-house/wagyu-key-gen/issues/51) with release build instructions. I performed all steps except signatures generation with no luck.

What could be a problem?

**Comment by remyroy** [comment]
Did you forget to run `yarn buildcli` on Unix or `yarn buildcliwin` on Windows? These need a python installation to work.

**Comment by SergeevDmitry** [comment]
Thank you for a fast reply. No, I did not forget any of this.

I run the following on my local Ubuntu 22.04
```
yarn install
yarn build
yarn buildcli
yarn dist
```

My pipeline for Windows runs the following

```
python -m pip install --upgrade --user pip
python -m pip install --user pyinstaller
python -m pip install --user Cython
npm install -g yarn
yarn install
yarn build
yarn buildcliwin
yarn dist
```

I use python 3.10 on both machines with all required packages installed

**Comment by SergeevDmitry** [comment]
The problem for Windows binary is solved. I had to run `yarn build` and `yarn buildcliwin` commands in separate pipline stages. But I still don't know what causes the problem on Ubuntu

**Comment by SergeevDmitry** [comment]
The problem with Ubuntu was that binary was build on version 22.04 and it cannot be run on version 20.04. Building on Ubuntu 20.04 allows to run binary on both versions.

Thank you for your time.

Closing it now
