### ISSUE TITLE
UX Tweaks in mnemonic generation

### ISSUE THREAD

**Issue by rhythnic** [stake-house/wagyu-key-gen#24]
- The color of the text for a generated mnemonic looks like an input field placeholder.  We should consider changing the color and maybe also sizing.
- The red text is hard to read on a dark gray background.  Red text is also associated with errors, but in this case the message is a warning.  Let's change the color of this message.
- UX to confirm that the mnemonic has been copied to the clipboard would be nice.  A Toast would work, or a temporary message below the copy button.

**Comment by colfax23** [comment]
Fixed,
