### ISSUE TITLE
Style Links on Secret Recovery Phrase info page

### ISSUE THREAD

**Issue by colfax23** [stake-house/wagyu-key-gen#32]
Let's have them use the same Yellow color as the discord, etc links do on the Home page, and no underline.  The default blue looks a bit harsh on the background. (cc @TheSquanch-147 know you worked on this recently, if this interests you)

**Comment by TheSquanch-147** [comment]
I'll give it a shot. I mentioned the coloring on my PR because at the time I was struggling with changing it but I'll figure it out this time.

**Comment by colfax23** [comment]
closed in #35
