### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by colfax23** [stake-house/wagyu-key-gen#37]
Let's get this application working on Windows.

**Comment by remyroy** [comment]
Let me try to get involved here

**Comment by remyroy** [comment]
Depends on #49

**Comment by remyroy** [comment]
With #49 completed, some slight changes to `Eth2Deposit.ts` is needed to call the right commands with the proper paths on Windows. I'll be working on that next.

**Comment by remyroy** [comment]
Work is started in https://github.com/remyroy/wagyu-key-gen/tree/python-bundling-win

**Comment by remyroy** [comment]
Depends on #60
