### ISSUE TITLE
Disable context isolation?

### ISSUE THREAD

**Issue by shawynot** [stake-house/wagyu-key-gen#45]
Is it a problem to disable `contextIsolation ` in /src/electron/index.ts? https://www.electronjs.org/docs/tutorial/context-isolation#security-considerations

**Comment by remyroy** [comment]
That was mentioned in #85

**Comment by remyroy** [comment]
My was, it might have been solved with that PR. @colfax23 ?

**Comment by remyroy** [comment]
This is related to or a duplicate of #11.
