### ISSUE TITLE
More robust error handling

### ISSUE THREAD

**Issue by shawynot** [stake-house/wagyu-key-gen#47]
Add more robust error handling to: 

- [ ] executecommand.ts
- [x] eth2deposit.ts

**Comment by remyroy** [comment]
Errors in eth2deposit.ts are not bubbling up and handled in the UI.

**Comment by remyroy** [comment]
code in executecommand.ts seems like it is not used anymore. Only used in readlink, uname and which in BashUtils.ts which aren't used anywhere. I guess all of this can be removed. Adding in new issue #91

**Comment by remyroy** [comment]
Close with the removal of executecommand.ts in #91
