### ISSUE TITLE
Make key creation folder clickable

### ISSUE THREAD

**Issue by Buttaa** [stake-house/wagyu-key-gen#58]
The path should be clickable to help users find their keys 

![image](https://user-images.githubusercontent.com/26490734/132998460-a2ae749d-bf5e-48c9-b1d8-9e58b8be1f97.png)

**Comment by remyroy** [comment]
shell.showItemInFolder might be useful here: https://www.electronjs.org/docs/latest/api/shell/#shellshowiteminfolderfullpath

**Comment by remyroy** [comment]
Let me give this a try.
