### ISSUE TITLE
Cross Platform Enhancements

### ISSUE THREAD

**Issue by colfax23** [stake-house/wagyu-key-gen#60]
List of cross platform enhancements that need to get done post this pr: https://github.com/stake-house/wagyu-key-gen/pull/56

- pwd and ls commands in BashUtils.ts
- doesFileExist will also have to be modified to work cross-platform. fs.accessSync can be used for that like in https://github.com/remyroy/wagyu-key-gen/blob/f3333263f824a0a7d6ec32a643a592dd1c31aa75/src/react/commands/Eth2Deposit.ts#L45

**Comment by remyroy** [comment]
I don't see pwd and ls being used anywhere. I've removed them.
