### ISSUE TITLE
Proper versioning

### ISSUE THREAD

**Issue by remyroy** [stake-house/wagyu-key-gen#67]
Let's do proper versioning. All our current build have the 1.0.0 version .

**Comment by remyroy** [comment]
This should include showing the version number in the app. @Buttaa where should that be shown?

**Comment by Buttaa** [comment]
> 
> 
> This should include showing the version number in the app. @Buttaa where should that be shown?

@remyroy 

![Figma_2021-09-16_17-16-47](https://user-images.githubusercontent.com/26490734/133638888-1bda6a1c-97df-4e20-a186-76597963db49.png)

We could also let the user know about updates. The link should forward to Github and should not automatically update for security reasaons. 

![Figma_2021-09-16_17-16-55](https://user-images.githubusercontent.com/26490734/133638967-049fcf68-27fb-4bde-b6e2-a16292ebba1b.png)

**Comment by remyroy** [comment]
There are 2 things here:

- display version number in UI
- add git id/sha/tag into version number and generally have a centralized location for version numbers

Display is now in #87 
This will be used for the somewhat *proper* versionning stuff which should be the other part.

**Comment by remyroy** [comment]
Actually, there is a third thing here that could be done in a seperate issue/PR:

- Check for updated version and ask for/link to update.
