### ISSUE TITLE
Move "close" button to the right

### ISSUE THREAD

**Issue by Buttaa** [stake-house/wagyu-key-gen#68]
![WagyuKeyGen_2021-09-16_17-29-25](https://user-images.githubusercontent.com/26490734/133641154-a94ad622-257e-401e-9d72-8d66f7139f77.png)

If we add a version info button (https://github.com/stake-house/wagyu-key-gen/issues/67#issuecomment-920995843) it will be clustered. An idea would be to move the "close" button the the right

**Comment by colfax23** [comment]
Implemented #67 and we had enough space.  Closing.
