### ISSUE TITLE
Automatically install missing dependencies

### ISSUE THREAD

**Issue by colfax23** [stake-house/wagyu-key-gen#8]
If there is a particular python package or other dependency that is not installed, let's detect it and install it.

**Comment by colfax23** [comment]
Here are two areas where you'll want to look:
 - create mnemonic command https://github.com/stake-house/wagyu-key-gen/blob/main/src/react/components/MnemonicGenerationWizard.tsx#L132
 - generate keys https://github.com/stake-house/wagyu-key-gen/blob/main/src/react/components/KeyGenerationWizard.tsx#L109

The commands are implemented in this file: https://github.com/stake-house/wagyu-key-gen/blob/main/src/react/commands/Eth2Deposit.ts

Let me know if you have any questions @EdwardCracknell or if you want to talk it through!  Thanks for working on this.

**Comment by EdwardCracknell** [comment]
Missing dependencies are: 
pycryptodome
eth_utils
py_ecc
ssz

which will be automatically set up to install via the pyinstaller

**Comment by EdwardCracknell** [comment]
Missing dependencies are: 
pycryptodome
eth_utils
py_ecc
ssz

which will be automatically set up to install via the pyinstaller

**Comment by remyroy** [comment]
I'll try to get involved and help you here if you don't mind @EdwardCracknell

**Comment by remyroy** [comment]
This is completed in my personal branch: https://github.com/remyroy/wagyu-key-gen/tree/python-bundling

**Comment by remyroy** [comment]
That branch does bundle everything in the single file executable and that SFE is used when creating a mnemonic or when generating keys. The resulting binary is in `dist/bin/eth2deposit_proxy`. It also needs word lists in `dist/word_lists`.

**Comment by remyroy** [comment]
The bundling can be starting by running the `src/scripts/bundle_proxy_linux.sh` on linux.

**Comment by remyroy** [comment]
I think we can close this now with the eth2deposit_proxy bundling scripts. What do you think @colfax23 ?
