### ISSUE TITLE
Does not create keys if chosen folder has a space

### ISSUE THREAD

**Issue by Buttaa** [stake-house/wagyu-key-gen#92]
Macos (Did not try on other OS yet)

If you choose a folder called `test keys` and want to create keys, the key gen says that the keys were generated but they were not. 

If you rename the folder to `testkeys` it works fine.

**Comment by remyroy** [comment]
It should have been fixed with f855268a3bd073ebea8d648ea0a73b13f9a49302

I'm guessing you used a non-dev version like the old 0.8. I would retry with the latest dev version if you want to build it.

**Comment by remyroy** [comment]
This should be retested with our latest dev version. @colfax23 can you bundle the latest dev on macOS for Butta to retest?

**Comment by Buttaa** [comment]
Tested, works now!

**Comment by remyroy** [comment]
#105 should fix even the cases we did not think about.
